# Generated by Django 5.1 on 2024-09-22 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('leetcode', models.URLField(blank=True, null=True)),
                ('gfg', models.URLField(blank=True, null=True)),
                ('hackerrank', models.URLField(blank=True, null=True)),
                ('hackerearth', models.URLField(blank=True, null=True)),
                ('other_link', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(default='Your Summary')),
                ('institution_10', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_10_location', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_10', models.CharField(blank=True, max_length=200, null=True)),
                ('end_year_10', models.IntegerField(blank=True, null=True)),
                ('board_10', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_type_10', models.CharField(blank=True, max_length=15, null=True)),
                ('percentage_10', models.FloatField(blank=True, null=True)),
                ('institution_12', models.CharField(max_length=100)),
                ('institution_12_location', models.CharField(default='xyz', max_length=100)),
                ('degree_12', models.CharField(max_length=200)),
                ('end_year_12', models.IntegerField(default='2024')),
                ('board_12', models.CharField(max_length=100)),
                ('grade_type_12', models.CharField(blank=True, max_length=15, null=True)),
                ('percentage_12', models.FloatField(blank=True, null=True)),
                ('college', models.CharField(max_length=100)),
                ('college_location', models.CharField(default='xyz', max_length=100)),
                ('degree_college', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('start_year_college', models.IntegerField(default=2021)),
                ('end_year_college', models.IntegerField(default=2024)),
                ('grade_type_college', models.CharField(blank=True, max_length=15, null=True)),
                ('percentage_college', models.FloatField(blank=True, null=True)),
                ('languages', models.CharField(max_length=500)),
                ('frameworks', models.CharField(blank=True, max_length=500, null=True)),
                ('other_skills', models.CharField(blank=True, max_length=500, null=True)),
                ('project_title_1', models.CharField(max_length=100)),
                ('project_description_1', models.TextField()),
                ('technologies_used_1', models.CharField(max_length=200)),
                ('project_link_1', models.URLField(blank=True, null=True)),
                ('project_title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description_2', models.TextField(blank=True, null=True)),
                ('technologies_used_2', models.CharField(blank=True, max_length=200, null=True)),
                ('project_link_2', models.URLField(blank=True, null=True)),
                ('job_title_1', models.CharField(blank=True, max_length=100, null=True)),
                ('job_mode_1', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date_1', models.DateField(blank=True, null=True)),
                ('end_date_1', models.DateField(blank=True, null=True)),
                ('job_description_1', models.TextField(blank=True, null=True)),
                ('job_title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('job_mode_2', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date_2', models.DateField(blank=True, null=True)),
                ('end_date_2', models.DateField(blank=True, null=True)),
                ('job_description_2', models.TextField(blank=True, null=True)),
                ('award', models.TextField(blank=True, max_length=2000, null=True)),
                ('certifications', models.TextField(blank=True, max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
